"""
Generated by generative AI
"""

from PySide6.QtWidgets import (
    QDialog, QVBoxLayout, QLabel, QPushButton,
    QFileDialog, QHBoxLayout
)
from PySide6.QtCore import Qt


class ProjectChoiceDialog(QDialog):
    NEW_PROJECT = "new"
    OPEN_PROJECT = "open"
    CANCEL = None

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Start Project")
        self.setModal(True)

        self.choice = self.CANCEL
        self.project_path = None

        self._build_ui()

    def _build_ui(self):
        layout = QVBoxLayout(self)

        label = QLabel("What would you like to do?")
        label.setAlignment(Qt.AlignCenter)
        layout.addWidget(label)

        button_layout = QHBoxLayout()

        new_btn = QPushButton("New Project")
        open_btn = QPushButton("Open Project")
        cancel_btn = QPushButton("Cancel")

        new_btn.clicked.connect(self._new_project)
        open_btn.clicked.connect(self._open_project)
        cancel_btn.clicked.connect(self.reject)

        button_layout.addWidget(new_btn)
        button_layout.addWidget(open_btn)
        button_layout.addWidget(cancel_btn)

        layout.addLayout(button_layout)

    def _new_project(self):
        self.choice = self.NEW_PROJECT
        self.accept()

    def _open_project(self):
        path, _ = QFileDialog.getOpenFileName(
            self,
            "Open Project",
            "",
            "Project Files (*.json *.loop);;All Files (*)"
        )
        if path:
            self.choice = self.OPEN_PROJECT
            self.project_path = path
            self.accept()
